# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.5.0
_src_path: gh:radio-aktywne/template-database-generic
accountname: radio-aktywne
databasename: howlite
description: Broadcast times data 🎭
docs: true
docsurl: https://radio-aktywne.github.io/howlite
envprefix: HOWLITE
imagename: databases/howlite
registry: true
releases: true
reponame: howlite
repourl: https://github.com/radio-aktywne/howlite
